server:
  port: 8080

spring:
  application:
    name: wolan
  thymeleaf:
    cache: false
    #prefix: file:${user.dir}/resources/templates/
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/www/resources/
