apiVersion: v1
kind: Pod
metadata:
  namespace: wolan
  name: pod-loki
  labels:
    app: pod-loki
spec:
  containers:
    - name: main
      image: grafana/loki:2.4.1
      ports:
        - containerPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  namespace: wolan
  name: svc-loki
spec:
  type: ClusterIP
  selector:
    app: pod-loki
  ports:
    - port: 3100
      targetPort: 3100
