version: "3"

services:
  svc-loki:
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

#  promtail:
#    image: grafana/promtail:2.4.0
#    volumes:
#      - /var/lib/docker/containers:/var/lib/docker/containers
#      - .:/etc/promtail
#    command: -config.file=/etc/promtail/config.yml
#    networks:
#      - loki

  svc-grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

networks:
  loki:
