apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wolan
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - condition:
                equals:
                  kubernetes.namespace: ccm-perf
              config:
                - type: container
                  paths:
                    - /var/log/containers/*-${data.kubernetes.container.id}.log
                  exclude_lines: [ "^\\s+[\\-`('.|_]" ]  # drop asciiart lines
    processors:
      - drop_fields:
          fields: [ "host", "tags", "ecs", "log", "prospector", "agent", "input", "beat", "offset", "kubernetes.node.labels" ]
          ignore_missing: true
    output.console:
      pretty: false
