#filebeat.inputs:
#  - type: log
#    enabled: true
#    paths:
#      - /var/log/*.log

filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition:
            equals:
              kubernetes.namespace: ccm-perf
          config:
            - type: container
              paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
              exclude_lines: [ "^\\s+[\\-`('.|_]" ]  # drop asciiart lines

processors:
  - drop_fields:
      fields: [ "agent", "container", "ecs", "kubernetes.node.labels", "log" ]
      ignore_missing: true

#output.console:

output.loki:
  hosts: [ 'svc-loki:3100' ]
