# kz build . | k --kubeconfig ~/Desktop/kc/kubeconfig.gimc-dev2 apply -f -
namespace: elk
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: promtail-config
    files:
      - promtail-config.yaml
resources:
  - ds_promtail.yaml
  - pod_grafana.yaml
  - pod_loki.yaml
  # base
  - ing.yaml
  - user.yaml
