apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wolan
  name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /var/log/positions.yaml # This location needs to be writeable by Promtail.
    
    client:
      url: http://svc-loki:3100/loki/api/v1/push
    
    scrape_configs:
      - job_name: system
        pipeline_stages:
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              host: yourhost
              __path__: /var/log/*.log
