server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml # This location needs to be writeable by Promtail.

client:
  url: http://svc-loki:3100/loki/api/v1/push

scrape_configs:
  - pipeline_stages:
      - docker: { }
    job_name: kubernetes-pods-name
    kubernetes_sd_configs:
      - role: pod
