apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: wolan
  name: wolan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wolan
rules:
  - apiGroups: [ "" ]
    resources:
      - nodes
      - services
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wolan
subjects:
  - kind: ServiceAccount
    namespace: wolan
    name: wolan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wolan
